### ISSUE TITLE
Flaky PerResourcePollingEventSourceTest

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1087]
```
Error:  Failures: 
Error:    PerResourcePollingEventSourceTest.getsValueFromCacheOrSupplier:97 
eventHandler.handleEvent(<any>);
Never wanted here:
-> at io.javaoperatorsdk.operator.processing.event.source.polling.PerResourcePollingEventSourceTest.getsValueFromCacheOrSupplier(PerResourcePollingEventSourceTest.java:97)
But invoked here:
-> at io.javaoperatorsdk.operator.processing.event.ExternalResourceCachingEventSource.handleEvent(ExternalResourceCachingEventSource.java:33) with arguments: [Event{relatedCustomResource=ResourceID{name='c83a1629-b833-4342-a02a-54d6781e3c96', namespace='test'}}]
-> at io.javaoperatorsdk.operator.processing.event.ExternalResourceCachingEventSource.handleDelete(ExternalResourceCachingEventSource.java:22) with arguments: [Event{relatedCustomResource=ResourceID{name='c83a1629-b833-4342-a02a-54d6781e3c96', namespace='test'}}]
-> at io.javaoperatorsdk.operator.processing.event.ExternalResourceCachingEventSource.handleEvent(ExternalResourceCachingEventSource.java:33) with arguments: [Event{relatedCustomResource=ResourceID{name='c83a1629-b833-4342-a02a-54d6781e3c96', namespace='test'}}]

[INFO] 

```

**Comment by csviri** [comment]
I don't see this anymore will close for now
