### ISSUE TITLE
Unable to connect K8s

### ISSUE THREAD

**Issue by WeiMingzhi** [java-operator-sdk/java-operator-sdk#1212]
I have a problem in connecting k8S.

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [CustomResourceDefinition]  with name: [timeoutcmds.ctl.cmg]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-5.3.1.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[kubernetes-client-5.3.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:224) ~[kubernetes-client-5.3.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:185) ~[kubernetes-client-5.3.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:86) ~[kubernetes-client-5.3.1.jar:?]
	at io.javaoperatorsdk.operator.Operator.register(Operator.java:146) ~[operator-framework-core-1.8.4.jar:?]
	at io.javaoperatorsdk.operator.Operator.register(Operator.java:97) ~[operator-framework-core-1.8.4.jar:?]
...
Caused by: javax.net.ssl.SSLHandshakeException: Failed to parse server certificates
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:320) ~[?:?]
...
Caused by: java.security.cert.CertificateParsingException: Empty issuer DN not allowed in X509Certificates
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:658) ~[?:?]
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169) ~[?:?]
...
```

This is my connection code
```
    io.fabric8.kubernetes.client.Config config = new ConfigBuilder().withMasterUrl("https://kubernetes.docker.internal:6443")
            .withTrustCerts(true)
            .withCaCertFile(caCerFile)
            .withClientCertFile(clientCertFile)
            .withClientKeyFile(clientKeyFile).build();

    return new DefaultKubernetesClient(config);
```
My three files are base64 from `~/.kube/config`,but error.
Could you help me,thanks.

**Comment by metacosm** [comment]
You shouldn't need to configure your client to connect to your cluster in most cases… Did you find that the default configuration didn't work for you?
