### ISSUE TITLE
Use PATCH without optimistick locking to remove finalizer this way will avoid conflicts

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1233]
For remove this makes sense in all cases.
(For add this could cause some issues, its hard to avoid "double adding" without optimistic locking" atm)

```
2022-05-24 14:19:26,505 i.j.o.p.e.ReconciliationDispatcher [ERROR] [flink.basic-session-job-example] Error during event processing ExecutionScope{ resource id: ResourceID{name='basic-session-job-example', namespace='flink'}, version: 854260} failed.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://127.0.0.1:55618/apis/flink.apache.org/v1beta1/namespaces/flink/flinksessionjobs/basic-session-job-example. Message: Operation cannot be fulfilled on flinksessionjobs.flink.apache.org "basic-session-job-example": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=flink.apache.org, kind=flinksessionjobs, name=basic-session-job-example, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on flinksessionjobs.flink.apache.org "basic-session-job-example": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:342)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:322)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleUpdate(BaseOperation.java:649)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:195)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:200)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:141)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:43)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher$CustomResourceFacade.replaceResourceWithLock(ReconciliationDispatcher.java:344)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.removeFinalizer(ReconciliationDispatcher.java:317)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleCleanup(ReconciliationDispatcher.java:283)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:78)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:55)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:356)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by csviri** [comment]
Hi @popdaniel942 , yes this is related to that. Will investigate that, it should not happen in general (or just rarely when the resource is updated while the reconciliatio running), so this issue will mitigate that. But will investigate why is that happening.

**Comment by csviri** [comment]
@popdaniel942 there is integration test on our side, that checks this, so it does not happen at least in normal flows:
https://github.com/java-operator-sdk/java-operator-sdk/blob/49ee0a03f90fdeb72a5f5cdd8d1477ef4329eeb3/operator-framework/src/test/java/io/javaoperatorsdk/operator/ControllerExecutionIT.java#L69-L71

If you could tell more in what situation this heppens to you would be very helpful. Isn't you code open source?  thx

**Comment by popdaniel942** [comment]
apparently with 3.0.1 this example works

**Comment by csviri** [comment]
@popdaniel942  thank you! we were able to reproduce this on an other project too, I'm on it! :)

**Comment by popdaniel942** [comment]
In our full code it still doesn't work with 3.0.1. But we don't change anything in the resource In the cleanup. All we do is call some rest methods. And when DeleteControl.defaultDelete() is called it fails. And after the retry it works.

**Comment by csviri** [comment]
Yes, this happens because the framework tried to remove the finalizer during a default delete. And the resource it sees in cache might have a different version than on the server. This is strange because once a resource is marked for deletion it cannot be changed, only finalizer removed. So if there are no more finalizers used, it's weird. But also since the cleanup is triggered is means that the resource (in memory) is already marked for deletion. Looking into it..

**Comment by csviri** [comment]
@popdaniel942 could you pls turn on debug level logs, with MDC values, and thread id present, something like this:
```
appender.console.layout.pattern = %style{%d}{yellow} "%tid" %style{%-30c{1.}}{cyan} %highlight{[%-5level] [%X{resource.namespace}.%X{resource.name}.%X{resource.resourceVersion}] %msg%n%throwable}
```
and send us the log files pls?  thx!

**Comment by csviri** [comment]
@popdaniel942 are you using `UpdateControl.patchStatus` to update the resource?

**Comment by popdaniel942** [comment]
Right now we are using UpdateControl.updateStatus but we got the error with both. What is the difference between them? Also I see that when the cleanup is made there is a foregroungDeletion finalizer being added and that the resourceVersion gets changed. Also in some cases, if we run the code in debug mode with breakpoints on the cleanup method we get the error, but if we run normally without debug mode, we don't get the error

**Comment by csviri** [comment]
It seems to be that I found the problem. It is actually not a bug, but this issue (using patch for finalizer removal) will fix it, see details here:
https://github.com/java-operator-sdk/java-operator-sdk/issues/1245

**Comment by csviri** [comment]
> Right now we are using UpdateControl.updateStatus but we got the error with both. What is the difference between them? 

its described here what can go wrong with the patch and why: https://github.com/java-operator-sdk/java-operator-sdk/issues/1245#issue-1250503818

```
One possible scenario that likely causes this is the following: when a resource reconciliation is in progress the resource gets deleted (like using kubectl, or other controller). The event for this delete is received. But at the end of the reconciliation to update the resource status a patch request (without optimistic locking) is executed. Since there is already an event present (the mar for delete event) the resource is submitted instantly for reconciliation. Note that the event for the status patch is not necessarily received at this point. So at the end of the cleanup the finalize removal uses a stale resource version.

Note that this not happened before because the UpdateControl.updateStatus is using optimistick locking and additional mechanisms to cache the resource that is the result of the update. This can happen just with UpdateControl.patchStatus
```

> Also I see that when the cleanup is made there is a foregroungDeletion finalizer being added and that the resourceVersion gets changed.

In this case it probably happened also occasionally before, since the finalizer removal is using optimistic locking (OL)  ATM (this issues will change that) 

> Also in some cases, if we run the code in debug mode with breakpoints on the cleanup method we get the error, but if we run normally without debug mode, we don't get the error.

This is probably caused because if you debug (it takes some time) to other finalizer is removed, or the resource is changed in other way.

**Comment by csviri** [comment]
> In case of updateStatus (since there is OL) it easy to cache the resource after the update, and ensure that next reconciliation has starts with newest one. 

If interested more in depth an see why is this possible pls check this:
https://github.com/fabric8io/kubernetes-client/pull/3943#issuecomment-1097171960

**Comment by csviri** [comment]
Ok so the issue should be solved by this PR:
https://github.com/java-operator-sdk/java-operator-sdk/pull/1249

Feel free to try ti out already with a local build from that branch.

At the end it won't be patch, but the update will be retried, see the reasons in the related issue:
https://github.com/java-operator-sdk/java-operator-sdk/issues/1248

Hopefully the issue will be merged soon, and a new patch version released.
