### ISSUE TITLE
Unexpected value in target namespaces: [JOSDK_ALL_NAMESPACES] 

### ISSUE THREAD

**Issue by morhidi** [java-operator-sdk/java-operator-sdk#1264]
JOSDK does not allow switching between watching all namespaces vs managed namespaces, when dynamic namespaces are enabled:

```
flink-kubernetes-operator io.javaoperatorsdk.operator.OperatorException: Unexpected value in target namespaces: [JOSDK_ALL_NAMESPACES]                                                     │
flink-kubernetes-operator     at io.javaoperatorsdk.operator.processing.Controller.changeNamespaces(Controller.java:331)                                                                   │
flink-kubernetes-operator     at org.apache.flink.kubernetes.operator.FlinkOperator.lambda$changeNamespaces$5(FlinkOperator.java:197)                                                      │
flink-kubernetes-operator     at java.base/java.lang.Iterable.forEach(Unknown Source)                                                                                                      │
flink-kubernetes-operator     at org.apache.flink.kubernetes.operator.FlinkOperator.changeNamespaces(FlinkOperator.java:193)                                                               │
flink-kubernetes-operator     at org.apache.flink.kubernetes.operator.config.FlinkConfigManager.updateDefaultConfig(FlinkConfigManager.java:131)                                           │
flink-kubernetes-operator     at org.apache.flink.kubernetes.operator.config.FlinkConfigManager$ConfigUpdater.run(FlinkConfigManager.java:212)                                             │
flink-kubernetes-operator     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)                                                                             │
flink-kubernetes-operator     at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)                                                                                     │
flink-kubernetes-operator     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)                                                        │
flink-kubernetes-operator     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                                                                               │
flink-kubernetes-operator     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                                                                              │
flink-kubernetes-operator     at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by morhidi** [comment]
cc @csviri
