### ISSUE TITLE
No custom resource has been found for controller

### ISSUE THREAD

**Issue by Mallington** [java-operator-sdk/java-operator-sdk#292]
I have been upgrading my operator to the java operator sdk version 1.5.0. I have encountered the following error:
```
Caused by: java.lang.IllegalArgumentException: No custom resource has been found for controller company.customoperator.dboperator.controller.AtpConnectionController
        at io.javaoperatorsdk.operator.ControllerUtils.getCustomResourceClass(ControllerUtils.java:46) ~[operator-framework-1.5.0.jar!/:?]
        at io.javaoperatorsdk.operator.Operator.registerController(Operator.java:68) ~[operator-framework-1.5.0.jar!/:?]
        at io.javaoperatorsdk.operator.Operator.registerControllerForAllNamespaces(Operator.java:47) ~[operator-framework-1.5.0.jar!/:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at company.customoperator.dboperator.application.DBOperatorConfiguration.operator(DBOperatorConfiguration.java:105) ~[classes!/:1.6.0-SNAPSHOT]
        at company.customoperator.dboperator.application.DBOperatorConfiguration$$EnhancerBySpringCGLIB$$6df6a4cf.CGLIB$operator$0(<generated>) ~[classes!/:1.6.0-SNAPSHOT]
        at company.customoperator.dboperator.application.DBOperatorConfiguration$$EnhancerBySpringCGLIB$$6df6a4cf$$FastClassBySpringCGLIB$$b47b1249.invoke(<generated>) ~[classes!/:1.6.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.17.RELEASE.jar!/:5.1.17.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.17.RELEASE.jar!/:5.1.17.RELEASE]
        at company.customoperator.dboperator.application.DBOperatorConfiguration$$EnhancerBySpringCGLIB$$6df6a4cf.operator(<generated>) ~[classes!/:1.6.0-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.17.RELEASE.jar!/:5.1.17.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.17.RELEASE.jar!/:5.1.17.RELEASE]
        ... 27 more

```
Setup:
- I am using the spring spring-boot-operator-framework-starter dependency
- I have specfied a controller using the @Controller annotation on a class which specifies the CustomResource
- I have also specified the controller in my configuration
- I have also applied the custom resource definition yaml
Problem:
The controllerToCustomResourceMappings method in the java operator sdk class ControllerUtils doesn't seem to find the CustomResourceClass, therefore returning null and throwing an IllegalArgumentException:
```java
static <R extends CustomResource> Class<R> getCustomResourceClass(
      ResourceController<R> controller) {
    final Class<? extends CustomResource> customResourceClass =
        controllerToCustomResourceMappings.get(controller.getClass());
    if (customResourceClass == null) {
      throw new IllegalArgumentException(
          String.format(
              "No custom resource has been found for controller %s",
              controller.getClass().getCanonicalName()));
    }
    ...
```
Any Ideas? Thank you in advance

**Comment by adam-sandor** [comment]
Thanks for reporting this issue @Mallington ! We will look into it asap

**Comment by Mallington** [comment]
@adam-sandor I have fixed it. I believe this was an issue with the way I had configured my project. Putting a configuration class directly into the same module as the java operator sdk seemed to fix it. Before, I had the controller and the `@Configuration` in sepearate modules.

**Comment by adam-sandor** [comment]
Ah ok, that's great. Tbh we are more focused on Quarkus right now than Spring Boot, so we might miss some problems. Please keep the feedback coming if you find anything else.
