### ISSUE TITLE
404 page not found on custom resource creation

### ISSUE THREAD

**Issue by daniellavoie** [java-operator-sdk/java-operator-sdk#339]
## Overview

I've been iterating on the implementation of a custom resource controller. I was able to get my `createOrUpdateResource` function called successfully. This CRD was initially configured with a `cluster` scope. After deleting it and recreating it with a `namespaced` scope, `createOrUpdateResource` is not called anymore and the ADDED event tries to update the resource with a finalizer. 

I have tested `v1.7.1` as well as `v.1.7.2-SNAPSHOT` and get the same result. 

I tried renaming the groupId to register a new fresh CRD and the problem is reproductible.

## Logs

```
2021-02-12 10:45:41.222  INFO 37585 --- [           main] io.javaoperatorsdk.operator.Operator     : Registered Controller: 'PinotClusterController' for CRD: 'class io.test.pinot.operator.resources.PinotCluster' for namespaces: [all namespaces]
2021-02-12 10:45:41.238 DEBUG 37585 --- [99.108:8443/...] i.j.o.p.e.i.CustomResourceEventSource    : Event received for action: ADDED, resource: test-local
2021-02-12 10:45:41.239 DEBUG 37585 --- [99.108:8443/...] i.j.o.processing.DefaultEventHandler     : Received event: CustomResourceEvent{action=ADDED, resource=[ name=test-local, kind=PinotCluster, apiVersion=test.io/v1 ,resourceVersion=1644270, markedForDeletion: false ]}
2021-02-12 10:45:41.274 DEBUG 37585 --- [99.108:8443/...] i.j.o.processing.DefaultEventHandler     : Executing events for custom resource. Scope: ExecutionScope{events=[CustomResourceEvent{action=ADDED, resource=[ name=test-local, kind=PinotCluster, apiVersion=test.io/v1 ,resourceVersion=1644270, markedForDeletion: false ]}], customResource uid: e2476a15-6d09-44b5-9608-5ca91941f3e8, version: 1644270}
2021-02-12 10:45:41.413  INFO 37585 --- [           main] i.s.p.o.s.PinotOperatorServer    : Started PinotOperatorServer in 2.2 seconds (JVM running for 2.693)
2021-02-12 10:45:46.157 DEBUG 37585 --- [ustercontroller] i.j.operator.processing.EventDispatcher  : Handling events: [CustomResourceEvent{action=ADDED, resource=[ name=test-local, kind=PinotCluster, apiVersion=test.io/v1 ,resourceVersion=1644270, markedForDeletion: false ]}] for resource ObjectMeta(annotations={kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"test.io/v1","kind":"PinotCluster","metadata":{"annotations":{},"name":"test-local","namespace":"default"},"spec":{"broker":{"profile":"small","replicas":1},"controller":{"profile":"small","replicas":1},"minion":{"profile":"small","replicas":1},"server":{"profile":"small","replicas":1},"zookeeper":{"profile":"small","replicas":1}}}
}, clusterName=null, creationTimestamp=2021-02-12T15:29:56Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=1, labels=null, managedFields=[ManagedFieldsEntry(apiVersion=test.io/v1, fieldsType=FieldsV1, fieldsV1=FieldsV1(additionalProperties={f:metadata={f:annotations={.={}, f:kubectl.kubernetes.io/last-applied-configuration={}}}, f:spec={.={}, f:broker={.={}, f:profile={}, f:replicas={}}, f:controller={.={}, f:profile={}, f:replicas={}}, f:minion={.={}, f:profile={}, f:replicas={}}, f:server={.={}, f:profile={}, f:replicas={}}, f:zookeeper={.={}, f:profile={}, f:replicas={}}}}), manager=kubectl-client-side-apply, operation=Update, time=2021-02-12T15:29:56Z, additionalProperties={})], name=test-local, namespace=default, ownerReferences=[], resourceVersion=1644270, selfLink=/apis/test.io/v1/namespaces/default/pinotclusters/test-local, uid=e2476a15-6d09-44b5-9608-5ca91941f3e8, additionalProperties={})
2021-02-12 10:45:46.160 DEBUG 37585 --- [ustercontroller] i.j.operator.processing.EventDispatcher  : Adding finalizer for resource: e2476a15-6d09-44b5-9608-5ca91941f3e8 version: 1644270
2021-02-12 10:45:46.160 DEBUG 37585 --- [ustercontroller] i.j.operator.processing.EventDispatcher  : Trying to replace resource test-local, version: 1644270
2021-02-12 10:45:46.189 ERROR 37585 --- [ustercontroller] i.j.operator.processing.EventDispatcher  : Error during event processing ExecutionScope{events=[CustomResourceEvent{action=ADDED, resource=[ name=test-local, kind=PinotCluster, apiVersion=test.io/v1 ,resourceVersion=1644270, markedForDeletion: false ]}], customResource uid: e2476a15-6d09-44b5-9608-5ca91941f3e8, version: 1644270} failed.

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://192.168.99.108:8443/apis/test.io/v1/pinotclusters/test-local. Message: 404 page not found
.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:509) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:286) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:267) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:876) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$0(HasMetadataOperation.java:75) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:80) ~[kubernetes-client-5.0.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:30) ~[kubernetes-client-5.0.0.jar:na]
	at io.javaoperatorsdk.operator.processing.EventDispatcher$CustomResourceFacade.replaceWithLock(EventDispatcher.java:199) ~[classes/:na]
	at io.javaoperatorsdk.operator.processing.EventDispatcher.replace(EventDispatcher.java:173) ~[classes/:na]
	at io.javaoperatorsdk.operator.processing.EventDispatcher.updateCustomResourceWithFinalizer(EventDispatcher.java:150) ~[classes/:na]
	at io.javaoperatorsdk.operator.processing.EventDispatcher.handleCreateOrUpdate(EventDispatcher.java:91) ~[classes/:na]
	at io.javaoperatorsdk.operator.processing.EventDispatcher.handleDispatch(EventDispatcher.java:79) ~[classes/:na]
	at io.javaoperatorsdk.operator.processing.EventDispatcher.handleExecution(EventDispatcher.java:46) ~[classes/:na]
	at io.javaoperatorsdk.operator.processing.ExecutionConsumer.run(ExecutionConsumer.java:25) ~[classes/:na]
```

## CRD

```
Name:         pinotclusters.test.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-02-12T15:29:26Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:conditions:
    Manager:      kube-apiserver
    Operation:    Update
    Time:         2021-02-12T15:29:26Z
    API Version:  apiextensions.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:preserveUnknownFields:
        f:scope:
        f:version:
        f:versions:
      f:status:
        f:storedVersions:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-02-12T15:29:26Z
  Resource Version:  1644248
  Self Link:         /apis/apiextensions.k8s.io/v1/customresourcedefinitions/pinotclusters.test.io
  UID:               887f0582-6db1-414b-af44-7442eda2c763
Spec:
  Conversion:
    Strategy:  None
  Group:       test.io
  Names:
    Kind:       PinotCluster
    List Kind:  PinotClusterList
    Plural:     pinotclusters
    Short Names:
      pinot
    Singular:               pinotcluster
  Preserve Unknown Fields:  true
  Scope:                    Namespaced
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       PinotCluster
    List Kind:  PinotClusterList
    Plural:     pinotclusters
    Short Names:
      pinot
    Singular:  pinotcluster
  Conditions:
    Last Transition Time:  2021-02-12T15:29:26Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-02-12T15:29:26Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>
```

## Custom Resource

```
kubectl describe pinotcluster test-local
Name:         test-local
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  test.io/v1
Kind:         PinotCluster
Metadata:
  Creation Timestamp:  2021-02-12T15:29:56Z
  Generation:          1
  Managed Fields:
    API Version:  test.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:broker:
          .:
          f:profile:
          f:replicas:
        f:controller:
          .:
          f:profile:
          f:replicas:
        f:minion:
          .:
          f:profile:
          f:replicas:
        f:server:
          .:
          f:profile:
          f:replicas:
        f:zookeeper:
          .:
          f:profile:
          f:replicas:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-02-12T15:29:56Z
  Resource Version:  1644270
  Self Link:         /apis/test.io/v1/namespaces/default/pinotclusters/test-local
  UID:               e2476a15-6d09-44b5-9608-5ca91941f3e8
Spec:
  Broker:
    Profile:   small
    Replicas:  1
  Controller:
    Profile:   small
    Replicas:  1
  Minion:
    Profile:   small
    Replicas:  1
  Server:
    Profile:   small
    Replicas:  1
  Zookeeper:
    Profile:   small
    Replicas:  1
Events:        <none>
```

**Comment by metacosm** [comment]
Hi @daniellavoie, sorry for the late reply, somehow I missed this issue.

Does your `PinotCluster` class implement `Namespaced`?

**Comment by daniellavoie** [comment]
Maybe next time i will read the documentation ENTIRELY...

Thank you! Still I would like to keep this issue open as I'll try to contribute a PR that provides an explicit exception when the CRD is defined as `Namespaced` and the interface missing. I believe the sdk has all the required information to make that check.

**Comment by metacosm** [comment]
@daniellavoie I've thought about doing something like this at the fabric8 client level but it might indeed be useful at the SDK level. We're also considering changing that behavior because it makes more sense for resources to be namespaced by default and that clustered resources should be marked explicitly. In the mean time, it might indeed make sense to report an error to SDK users. I'll let you handle it if you'd like. Let me know if you need help with it.
