### ISSUE TITLE
Event sources for the same resource type in multiple namespaces

### ISSUE THREAD

**Issue by bearpaws** [java-operator-sdk/java-operator-sdk#915]
With version 1.10.x of the SDK, event sources for the same type but different namespaces can be registered:

```java
public void init(EventSourceManager eventSourceManager)
{
  SharedIndexInformer<Deployment> informer1 = client.apps().deployments()
    .inNamespace("ns1").withLabel("a", "b").runnableInformer(0);

  SharedIndexInformer<Deployment> informer2 = client.apps().deployments()
    .inNamespace("ns2").withLabel("a", "b").runnableInformer(0);

  InformerEventSource<Deployment> source1 = new InformerEventSource<>(informer1, ...);
  InformerEventSource<Deployment> source2 = new InformerEventSource<>(informer2, ...);

  eventSourceManager.registerEventSource("source1", source1);
  eventSourceManager.registerEventSource("source2", source2);
}
```

Using the same strategy in 2.1.1 produces an exception:

```java
public List<EventSource> prepareEventSources(EventSourceContext<MyResource> context)
{
  SharedIndexInformer<Deployment> informer1 = client.apps().deployments()
    .inNamespace("ns1").withLabel("a", "b").runnableInformer(0);

  SharedIndexInformer<Deployment> informer2 = client.apps().deployments()
    .inNamespace("ns2").withLabel("a", "b").runnableInformer(0);

  return List.of(
    new InformerEventSource<>(informer1, Mappers.fromOwnerReference()),
    new InformerEventSource<>(informer2, Mappers.fromOwnerReference()));
}
```

```
java.lang.IllegalArgumentException: An event source is already registered for the (io.fabric8.kubernetes.api.model.apps.Deployment, io.javaoperatorsdk.operator.processing.event.source.informer.InformerEventSource) class/name combination
    at io.javaoperatorsdk.operator.processing.event.EventSourceManager$EventSources.add(EventSourceManager.java:216)
    at io.javaoperatorsdk.operator.processing.event.EventSourceManager.registerEventSource(EventSourceManager.java:107)
```

Is there an alternative way to implement this in v2?  This conversation implies it's still supported:
https://github.com/java-operator-sdk/java-operator-sdk/issues/827

**Additional context:**

The operator is configured to watch specific namespaces:
```java
ControllerConfiguration<MyResource> baseConfig = DefaultConfigurationService.instance().getConfigurationFor(controller);
ControllerConfiguration<MyResource> config = ControllerConfigurationOverrider
    .override(baseConfig)
    .addingNamespaces("ns1", "ns2")
    .build();
operator.register(controller, config);
```

**Environment:**

Kube version 1.21
SDK version 2.1.1

**Comment by csviri** [comment]
hi @bearpaws , yes you have just to rename on of the event sources, there is a default name added, but the combination of name/type is unique. Just renaming one of the event sources should fix this.

**Comment by metacosm** [comment]
More precisely, you need to override the `name` method in one of your event sources, for example by doing:
```java
public List<EventSource> prepareEventSources(EventSourceContext<MyResource> context)
{
  SharedIndexInformer<Deployment> informer1 = client.apps().deployments()
    .inNamespace("ns1").withLabel("a", "b").runnableInformer(0);

  SharedIndexInformer<Deployment> informer2 = client.apps().deployments()
    .inNamespace("ns2").withLabel("a", "b").runnableInformer(0);

  return List.of(
    new InformerEventSource<>(informer1, Mappers.fromOwnerReference()),
    new InformerEventSource<>(informer2, Mappers.fromOwnerReference()) {
      @Override
      public String name() {
        return "informerFromNS2";
      }
    });
}
```

**Comment by metacosm** [comment]
And it should also be exposed in the dependent resource configuration as well.

**Comment by bearpaws** [comment]
Thanks @csviri and @metacosm - overriding the name fixed it.  Yes, a constructor argument for the name would help to clarify.

**Comment by metacosm** [comment]
Keeping this open to add the name to constructor and associated configuration

**Comment by csviri** [comment]
Closing this, since InformerEventSource supports more namespaces out of the box from 3.0
